### PR TITLE
Removes files from S3 for a release (moves to /broken/)

### PR DESCRIPTION
**Pull request by gabriel**
@MarcoPolo

### CODE REVIEW

**Comment by gabriel** [comment]
Slack side: https://github.com/keybase/slackbot/pull/24

**Comment by gabriel** [comment]
@oconnor663 when marking a release as broken, I move files from a release to /broken/...

What files other than these should I move for linux:

```go
	case "deb":
		return []string{
			// TODO: Get full file list from jack
			fmt.Sprintf("linux_binaries/deb/keybase_%s_i386.deb", release.Version),
			fmt.Sprintf("linux_binaries/deb/keybase_%s_amd64.deb", release.Version),
		}
	case "rpm":
		return []string{
			// TODO: Get full file list from jack
			fmt.Sprintf("linux_binaries/rpm/keybase-%s-1.x86_64.rpm", release.Version),
			fmt.Sprintf("linux_binaries/rpm/keybase-%s-1.i386.rpm", release.Version),
		}
```

**Comment by oconnor663** [comment]
@gabriel sorry for leaving you hanging here. We can do a hangout tomorrow if you want to go over it?

**Comment by gabriel** [comment]
yeah sure

**Pull request merged**
